### ISSUE TITLE
websocket

### ISSUE THREAD

**Issue by stefanocudini** [dmitryame/echowaves#4]
hi dmitry

I went for a long time ago if I'm on echowaves.com i'm stefano Italian developer does not know if you remember me, we talked about your Project almost one year ago

Lately I've been experimenting the websocket with the client and server side
I noticed that many of the current version of browsers begin to support websocket.
and so I came back to your interesting project

I thought I could have already incorporated this technology into your project?
I think it would be very interesting

**Comment by dmitryame** [comment]
Hi Stefano,
good to hear from you again,
well, yeah, i've been looking at web sockets for a while now and definitely will implement them in the next release.
Unfortunately i'm currently working on some other projects and do not have much time to devote to the EW, but eventually -- yes. As a matter of fact I already started the EW2 -- a complete rewrite (which is a closed sorse for now), but honestly I don't know how long it will take me to complete before i can release it to public.
